chore: sync v3 with main
googleapis/python-bigquery pull request #1004
Opened 2021-10-06 15:35 UTC by tswast

Thought: maybe if we merge this as a merge commit, we can avoid some conflicts the next time we sync?

2021-10-06 15:45 UTC, tswast commented on google/cloud/bigquery/table.py
> +
Duplicate

```suggestion
```

2021-10-07 18:41 UTC, tseaver commented
@tswast I think the change to the samples image is [forthcoming soon](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/6813).

2021-10-16 10:31 UTC, plamut requested changes
It seems fine, apart from the intersphinx links that should be retained.

The unit tests still produce no warnings, and the `skipif` decorators in tests do not check for dependencies that have been made required in `v3` (BQ storage, pyarrow...) - these are the two main things that can sneak in without a merge conflict, as far as I can remember.

2021-10-16 10:31 UTC, plamut commented on owlbot.py
> -        "protobuf": ("https://googleapis.dev/python/protobuf/latest/", None),
IIRC these were added these ack when we re-added legacy proto-based types to `v3`. We should thus retain them.

2021-10-16 10:31 UTC, plamut commented on owlbot.py
> -s.replace("docs/conf.py", r'\s+"(proto-plus|protobuf)":.*$', "")
Related to the comment above, we actually want to include proto* intersphinx links.

2021-10-16 10:34 UTC, plamut commented
Added the `do not merge` label as an explicit reminder to use a _merge commit_ when merging this (do NOT squash). Hopefully the person who eventually merges this will notice this comment when seeking the reason why the label was added in the first place. :upside_down_face:

2021-10-28 06:56 UTC, plamut approved these changes

2021-10-28 06:57 UTC, merged