explicitly add bq to samples reqs, upgrade grpc to fix bug on m1
googleapis/python-bigquery pull request #1290
Opened 2022-07-15 19:14 UTC by leahecole

Related to #1260 and #1262

Can confirm these linked issues definitely happen with M1, but is fixed if you specifically add grpc as an explicit dependency

2022-07-15 23:29 UTC, loferris requested changes
Hi @leahecole, looking at the system test failures, I think we can fix this if we update the required versions in `setup.py` (project root) and the constraint files for at least 3.8 and 3.10 in the `testing` folder (project root).

2022-07-16 15:00 UTC, parthea approved these changes

2022-07-16 15:01 UTC, parthea commented
Should we also update the grpc requirements in setup.py ? https://github.com/googleapis/python-bigquery/blob/main/setup.py#L32

2022-07-18 18:56 UTC, leahecole commented
> Hi @leahecole, looking at the system test failures, I think we can fix this if we update the required versions in `setup.py` (project root) and the constraint files for at least 3.8 and 3.10 in the `testing` folder (project root).

To clarify, the constraint being the grpc version, not the BQ version we also added, right, @loferris?

2022-07-18 20:37 UTC, loferris requested changes
Looking at the Kokoro failures, I'm seeing a flag to update the 3.7 constraints file (in the `testing` folder) to have the correct `grpcio` version. 
<img width="1104" alt="Screen Shot 2022-07-18 at 1 33 21 PM" src="https://user-images.githubusercontent.com/50979514/179612988-ecf56d3e-c712-4238-96f1-f4e1fb42f7f3.png">
.

2022-07-18 20:37 UTC, loferris commented
> > Hi @leahecole, looking at the system test failures, I think we can fix this if we update the required versions in `setup.py` (project root) and the constraint files for at least 3.8 and 3.10 in the `testing` folder (project root).
> 
> To clarify, the constraint being the grpc version, not the BQ version we also added, right, @loferris?

From what I can tell from the Kokoro test failures, that seems right to me!!

2022-07-19 12:12 UTC, parthea commented
`testing/constraints-3.6.txt` could be deleted since we're no longer supporting python 3.6

2022-07-19 13:56 UTC, leahecole commented
Ok! I'll make those changes. Thanks for the explanation - I've never touched these constraints files before so I wanted to be super sure I was doing the right thing 😁

2022-07-19 16:47 UTC, loferris commented on testing/constraints-3.10.txt
> +grpcio==1.47.0
I think we had to add this explicitly to get the system tests (if not, would be happy to delete!!), but I'd suggest I make a follow up issue to clean up the versioning across different versions.

2022-07-19 16:49 UTC, loferris approved these changes
I'm going to approve and merge, but I do want to follow up with @parthea about versioning overall.

2022-07-19 16:49 UTC, merged

2022-07-19 17:13 UTC, leahecole commented
SGTM - let me know what you end up deciding!