docs: Revised relax_column sample
googleapis/python-bigquery pull request #1467
Opened 2023-01-17 20:54 UTC by thejaredchapman

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Towards #790  🦕

2023-02-27 22:32 UTC, tswast approved these changes

2023-02-27 22:33 UTC, tswast requested changes
We should add a TODO to `snippets.py` (or wherever the old sample is) to remove it after updating cloud.google.com

2023-06-26 20:54 UTC, meredithslota commented
This is missing the CLA — we can either override this (see the CLA details) or close this and open a new PR, since the CLA violations were only in merging `main` into this branch.

2023-10-05 18:31 UTC, tswast commented
> This is missing the CLA — we can either override this (see the CLA details) or close this and open a new PR, since the CLA violations were only in merging main into this branch.

I'll rebase and force push to drop the bad merge commits.

2023-10-05 18:34 UTC, tswast approved these changes

2023-10-05 19:03 UTC, merged