Add default LoadJobConfig to Client
googleapis/python-bigquery pull request #1526
Opened 2023-03-14 23:01 UTC by chelsea-lin

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [X] Make sure to open an issue as a [issue](https://github.com/googleapis/python-bigquery/issues/1519) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [X] Ensure the tests and linter pass
- [X] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #1519 🦕

2023-03-15 13:54 UTC, tswast requested changes

2023-03-15 23:40 UTC, chelsea-lin commented on google/cloud/bigquery/client.py
I originally skipped them because `load_table_from_json` are calling `load_table_from_file` eventually. However, it's not hurt to fill them with the default load job in case they're diverse someday. Thanks for the suggestions. 

The `_get_default_load_job_config` could be similar to `_fill_from_default` in the `base.py`. Hence, I modified `_fill_from_default` to be applied for our usages. Hopefully it looks cleaner.

2023-03-15 23:41 UTC, chelsea-lin commented on google/cloud/bigquery/client.py
> +            job_config = copy.deepcopy(job_config)
Replied in other comments. Thanks.

2023-03-16 23:41 UTC, chelsea-lin commented on google/cloud/bigquery/client.py
> +        job_config = job_config._fill_from_default(self._default_load_job_config)
`job_config: LoadJobConfig` confuses `mypy` to re-define the parameter. Hence, I also rename it into `new_job_config`. Then, `mypy` tests pass now.

2023-03-17 20:03 UTC, tswast approved these changes

2023-03-17 20:03 UTC, merged