hotfix: handle case when expirationMs is None
googleapis/python-bigquery pull request #1553
Opened 2023-04-17 20:16 UTC by abdelmegahed

Right now, unsetting `['timePartitioning']['expirationMs']` on BigQuery table is not supported and raises `google.api_core.exceptions.BadRequest: 400 PATCH https://bigquery.googleapis.com/bigquery/v2/projects/abdelrahmanm-bd-dev/datasets/partition_expiry_test/tables/sample_data_partitioned?prettyPrint=false: Invalid value at 'table.time_partitioning.expiration_ms.value' (TYPE_INT64), "None"`

This happens since the backend doesn't treat "None" (string) as a null. This PR addresses this issue from the client side.

Sample code that fails with the above exception:
```
from google.cloud import bigquery
client = bigquery.Client(project='abdelrahmanm-bd-dev')
table_ref = client.dataset('partition_expiry_test').table('sample_data_partitioned')
table = client.get_table(table_ref)
table.partition_expiration = None # ISSUE HERE!! This get cast to string and the backend returns a 400 as a result.
client.update_table(table, ['partition_expiration'])
```

2023-04-18 19:16 UTC, tswast requested changes
Thanks @abdelmegahed 

Could you write a unit test covering this case? I'd expect one similar to https://github.com/googleapis/python-bigquery/blob/main/tests/unit/test_table.py#L1178 `test_to_api_repr_w_custom_field` perhaps called `test_to_api_repr_w_unsetting_expiration`

2023-04-18 21:54 UTC, abdelmegahed commented
@tswast test added. Thanks for the pointers :)

2023-04-19 00:04 UTC, abdelmegahed commented on tests/unit/test_table.py
> +        table._properties["timePartitioning"] = {"expirationMs": None}
Yeahh a test exist for that [here](https://github.com/googleapis/python-bigquery/blob/main/tests/unit/test_table.py#L1395). Now that you've mentioned this, I am thinking to test the None case there too?

2023-05-16 19:58 UTC, tswast approved these changes

2023-05-17 19:57 UTC, merged