fix: AccessEntry API representation parsing
googleapis/python-bigquery pull request #1682
Opened 2023-10-13 20:21 UTC by jonathan-ostrander

Overriding the `AccessEntry#_properties` with a deep copy of the API resource overwrites the `role` property set in `AccessEntry.__init__` which isn't present in the resource if the `role` is set to `None`. This causes `AccessEntry`s generated from API representations to no longer evaluate to equal with equivalent `AccessEntry` resources instantiated through `AccessEntry.__init__`. The added unit test fails without the change and passes with the change.

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #1681 🦕

2023-10-18 17:01 UTC, Linchin commented
Hi @jonathan-ostrander, thank you so much for your contribution! The PR looks good, but it seems the lint test failed. As seen in the kokoro results:
![image](https://github.com/googleapis/python-bigquery/assets/12806577/4a9bde53-5737-429f-b863-772b11fd48f9)

Please see the [instructions in the contribution doc](https://github.com/googleapis/python-bigquery/blob/main/CONTRIBUTING.rst#coding-style) for more info on coding style. If you need any help, please let us know! :)

2023-10-18 17:56 UTC, Linchin commented on tests/unit/test_dataset.py
please fix linting test

2023-10-18 17:57 UTC, Linchin requested changes
please fix linting error

2023-10-18 18:21 UTC, jonathan-ostrander commented
@Linchin should be fixed in [15153e6](https://github.com/googleapis/python-bigquery/pull/1682/commits/15153e6980e692a3c3a87085fd9be6a32ecea4b3) although I couldn't get nox working locally so I just ran black.

2023-10-19 19:59 UTC, Linchin approved these changes

2023-10-19 20:07 UTC, merged