perf(bigquery): remove redundant array deepcopy
googleapis/python-bigquery pull request #26
Opened 2020-02-06 09:31 UTC by grooveygr

Deepcopy can be a very costly operation when considering large arrays with complex nested objects.
Refactor helpers to allow recursive conversion without copying arrays.

Fixes #6 🦕

2020-07-30 18:10 UTC, tseaver commented
@plamut I'm less familiar than you with this bit of the code.  PTAL.

2020-09-24 21:17 UTC, tswast requested changes

2020-09-24 21:17 UTC, tswast commented on tests/unit/test__helpers.py
> +            _make_field("INT64", name="one"),
The main point of the `_single_field_to_json` function is that it ignores the `REPEATED` property, right? We should have tests that validate this behavior (that is: set mode = REPEATED in some fields)

2020-10-06 21:46 UTC, tswast approved these changes

2020-10-06 21:46 UTC, busunkim96 commented on google/cloud/bigquery/_helpers.py
> +    Ignores mode so that this can function for ARRAY / REPEATING fiels
```suggestion
    Ignores mode so that this can function for ARRAY / REPEATING fields
```

2020-10-06 21:47 UTC, tswast commented on google/cloud/bigquery/_helpers.py
> +    Ignores mode so that this can function for ARRAY / REPEATING fiels
thank you Bu Sun

2020-10-07 14:38 UTC, merged