fix: address job_congig.source_format
googleapis/python-bigquery pull request #262
Opened 2020-09-17 09:26 UTC by HemangChothani

Fixes #261

2020-09-17 14:15 UTC, tswast reviewed
Thanks for the quick response! A few suggested update to the error message.

2020-09-17 14:15 UTC, tswast commented on google/cloud/bigquery/client.py
> +                    "Cannot pass `{}` as a ``source_format``, currently PARQUET is supported".format(
```suggestion
                    "Got unexpected source_format: '{}'. Currently, only PARQUET is supported".format(
```

2020-09-17 14:15 UTC, tswast commented on tests/unit/test_client.py
> +        assert "Cannot pass" in str(exc.value)
```suggestion
        assert "Got unexpected source_format:" in str(exc.value)
```

2020-09-17 14:34 UTC, plamut requested changes
Seems fine apart from that gotcha that might bite us at some future point.

2020-09-17 14:34 UTC, plamut commented on google/cloud/bigquery/client.py
> +            if job_config.source_format is not job.SourceFormat.PARQUET:
This (non)identity check is relying on interning strings, but we shouldn't rely on `"PARQUET"` strings to point (or not point) to the same string instance. Let's use the equality operator instead.

(`SourceFormat` is not an `enum`, it's just a plain class with a few string members)

2020-09-18 14:11 UTC, tswast approved these changes

2020-09-18 14:11 UTC, merged