feat: allow client options to be set in magics context
googleapis/python-bigquery pull request #322
Opened 2020-10-13 07:08 UTC by cguardia

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #160 🦕

2020-10-13 16:36 UTC, tswast commented on google/cloud/bigquery/magics/magics.py
> +        "The desired API endpoint, e.g., compute.googlepis.com. Defaults to this "
Let's make the example bigquery-specific

```suggestion
        "The desired API endpoint, e.g., bigquery.googlepis.com. Defaults to this "
```

2020-10-13 16:36 UTC, tswast commented on google/cloud/bigquery/magics/magics.py
> +    "--api_endpoint",
We might actually want two API endpoints, one for the BigQuery client and one for the BigQuery Storage client.

2020-10-13 16:36 UTC, tswast commented on google/cloud/bigquery/magics/magics.py
> +    def client_options(self):
We might actually want two client options, one for the BigQuery client and one for the BigQuery Storage client.

2020-10-14 04:09 UTC, cguardia commented
@tswast OK, added both client options now.

2020-10-14 14:13 UTC, tswast requested changes
Looking good! Just one nit about naming

2020-10-14 18:24 UTC, cguardia commented on google/cloud/bigquery/magics/magics.py
> +    def storage_client_options(self):
Right. Done.

2020-10-14 18:33 UTC, tswast approved these changes

2020-10-14 18:42 UTC, merged

2020-10-15 05:56 UTC, boaz-work commented
Thanks