docs(samples): add more clustering code snippets
googleapis/python-bigquery pull request #330
Opened 2020-10-18 05:32 UTC by ryanyuan

Add sample code for creating a clustered table from a query result.
File: samples/client_query_destination_table_clustered.py
Section: [https://cloud.google.com/bigquery/docs/creating-clustered-tables#creating_a_clustered_table_from_a_query_result](https://cloud.google.com/bigquery/docs/creating-clustered-tables#creating_a_clustered_table_from_a_query_result)

Add sample code for creating a clustered table when you load data.
File: samples/load_table_clustered.py
Section: [https://cloud.google.com/bigquery/docs/creating-clustered-tables#creating_a_clustered_table_when_you_load_data](https://cloud.google.com/bigquery/docs/creating-clustered-tables#creating_a_clustered_table_when_you_load_data)

Fixes #329  🦕

2020-10-29 16:08 UTC, tswast requested changes
Thanks for the contribution! A couple of nits

2020-10-29 16:08 UTC, tswast commented on samples/client_query_destination_table_clustered.py
> +    # [START bigquery_query_destination_table_clustered]
We need to standardize with what the other languages are using.

```suggestion
    # [START bigquery_query_clustered_table]
```

2020-10-29 16:08 UTC, tswast commented on samples/client_query_destination_table_clustered.py
> +    # [END bigquery_query_destination_table_clustered]
```suggestion
    # [END bigquery_query_clustered_table]
```

2020-10-29 16:08 UTC, tswast commented on samples/load_table_clustered.py
> +    with open(file_path, "rb") as source_file:
Nit: The Go sample loads from GCS `"gs://cloud-samples-data/bigquery/sample-transactions/transactions.csv"`

It'd be nice if we had some consistency across languages. Also, it's a little bit simpler to run the sample without the need for local files.

Go sample:

https://github.com/GoogleCloudPlatform/golang-samples/blob/7c9a079be0894b2c04c825c07d55176e65087c88/bigquery/snippets/loadingdata/bigquery_load_table_clustered.go#L17-L70

2020-11-04 16:50 UTC, tswast approved these changes

2020-11-04 21:15 UTC, ryanyuan commented
@tswast thanks for the review and changes.

2020-11-16 17:17 UTC, engelke approved these changes
LGTM.

2020-11-17 16:04 UTC, merged