feat(bigquery): pass retry from Job.result() to Job.done().
googleapis/python-bigquery pull request #41
Opened 2020-02-21 09:51 UTC by IlyaFaer

2020-02-21 10:03 UTC, IlyaFaer commented
This PR is strictly connected to https://github.com/googleapis/python-api-core/pull/9, and should not be merged before №9

2020-02-21 10:28 UTC, IlyaFaer commented
Here is how it's gonna be passed into `done()`

![image](https://user-images.githubusercontent.com/26030071/75026394-f550a580-54ad-11ea-90ea-48d87ecbb61a.png)

2020-10-20 16:38 UTC, tswast commented
This will need to be updated to set the minimum api-core version in setup.py to 1.23.0 after https://github.com/googleapis/python-api-core/pull/96 is released.

2020-10-21 14:18 UTC, tswast commented
1.23.0 has been released. Work can continue on this PR

2020-10-22 09:08 UTC, IlyaFaer commented
Only one error is failing:
```
self = <google.cloud.bigquery.job._AsyncJob object at 0x7f1fc2f0eb70>

    def to_api_repr(self):
        """Generate a resource for the job."""
>       raise NotImplementedError("Abstract")
E       NotImplementedError: Abstract
```
Doesn't seem to be related.

2020-10-23 14:57 UTC, tswast requested changes
Missing update to minimum versions.

2020-10-23 14:57 UTC, tswast commented on google/cloud/bigquery/job.py
> +        kwargs = {} if retry is DEFAULT_RETRY else {"retry": retry}
We don't have to follow this pattern here. We just need to bump the minimum `google-api-core` dependency version in `setup.py` and our `constraints-X.txt` file(s).

2020-10-23 15:00 UTC, tswast commented
Filed https://github.com/googleapis/python-bigquery/issues/339 to look into the test failure. I've assigned to myself, as it might be related to some refactoring I recently completed.

2020-10-27 08:12 UTC, IlyaFaer commented
I think, a lot of tests will fail. And in many tests we'll have to add one more arg. That's why I've added the `kwargs` pattern.

2020-10-27 15:56 UTC, tswast commented
> I think, a lot of tests will fail. And in many tests we'll have to add one more arg. That's why I've added the kwargs pattern.

Okay, that makes sense. So long as we have some tests that have a custom retry, I'm okay with only populating it when it's something other than the default.

2020-11-02 14:21 UTC, HemangChothani commented
@googlebot I consent

2020-11-02 19:02 UTC, IlyaFaer commented
@tswast, sorry, I'm little bit besieged by tasks, not able to continue with this right now. @HemangChothani kindly agreed to take a look at this PR.

2020-11-02 19:52 UTC, tswast requested changes

2020-11-02 19:52 UTC, tswast commented on tests/unit/test_job.py
> +            query_resource_done,
We had a few places where custom retry was already supported. I'd like to see a few more exceptions to be totally sure that all API calls are getting the right retry object.

```suggestion
            exceptions.NotFound("not normally retriable"),
            query_resource_done,
            exceptions.NotFound("not normally retriable"),
```

2020-11-03 15:43 UTC, tswast approved these changes

2020-11-03 15:43 UTC, merged